### ISSUE TITLE
Create base VWSException

### ISSUE THREAD

**Issue by laymonage** [VWS-Python/vws-python#1271]
Hello,

First of all, thanks for the great package!

I'd like to propose a change regarding the custom exceptions.

Right now, all exceptions (*except*<sup>heh</sup> `ConnectionErrorPossiblyImageTooLarge`) extends directly from `Exception`. I think it's a good idea if you create a base exception, e.g. `VWSException`, and have all the other exceptions extend from it. This way, users can handle all exceptions that come from this package with a simple `except VWSException` (instead of the generic `except Exception` or specifying each exception).

If you agree, I can make a PR for this.
Thanks!

**Comment by adamtheturtle** [comment]
Hello @laymonage - do you have a use case for this, e.g. a case where you want to `except VWSException`? If so - go for it! Please make sure your changes are tested, too. I'm also happy to help out if needed.

**Comment by laymonage** [comment]
Hi @adamtheturtle, one use case I have in mind is that I want to catch the exceptions that might arise from this package, but I don't want to handle them individually. Listing all the exceptions one by one is a bit handful since I don't really care what the exception is. I don't want to use `Exception` because that also handles exceptions that don't come from this package.

Other than that, I think it's just nice to have a base `VWSException` so that all the exceptions in (and only in) this package have the same parent.

I can try creating it in the next few days.

**Comment by adamtheturtle** [comment]
Sounds good @laymonage .

**Comment by adamtheturtle** [comment]
And to clarify:

> Listing all the exceptions one by one is a bit handful since I don't really care what the exception is

This sounds like a good motivation - less code for your own codebase, and I'll assume that if it is useful for you it is useful for others.

> Other than that, I think it's just nice to have a base `VWSException` so that all the exceptions in (and only in) this package have the same parent.

This one is not a useful motivation for me as I prefer to work on concrete use cases.
