### ISSUE TITLE
running sample code is returning errors

### ISSUE THREAD

**Issue by kanakapalli** [VWS-Python/vws-python#2297]
python add_images_vuforia.py

TypeError: unsupported operand type(s) for |: 'type' and 'NoneType' at /site-packages/vws/reports.py",

**Comment by adamtheturtle** [comment]
@kanakapalli Thank you for the report. Please could you share:

* The code in `add_images_vuforia.py`
* The full traceback (so I can see, for example, which line is erroring)
* The Python version you are using
* The version of this library you are using

**Comment by adamtheturtle** [comment]
My expectation is that you are using Python 3.9 or older, which is not supported by the latest version of this library.
Please switch to Python 3.10 or above, or you can experiment with older versions of this library.

**Comment by adamtheturtle** [comment]
Closing this, but please re-open @kanakapalli if I can help further.
